assets={
	primitives:["plane","box","sphere","disc","cylinder","cone","torus"],
	skyboxes:["desert","dusk","hilly","rain","TropicalSunnyDay","city","snow1","hot","moon"],
	structures:["farm_barn_01.babylon","farm_silo_01.babylon","tipi.babylon","huts.babylon","coffin.babylon","fences.babylon","tower_lowpoly.obj","scene.gltf"],
	vegetations:["farm_tree_01.babylon","farm_stump_01.babylon","farm_rocks_01.babylon","tree1.babylon","tree2.babylon"],
	characters:["Joan.babylon","Vincent.babylon","minotour001.glb"],
	vehicles:["farm_tractor_01.babylon"],
	sounds:["door.mp3","forest-ambient.ogg","nature-ambiance.ogg","soft-forest-music.ogg","tractor.wav","hello.mp3","old_door.ogg","wind.ogg","birdsFlap.ogg"],
        water:["sea"]
};