vishvaFiles=[
  {"d":"assets",
   "f":[
    {"d":"characters",
     "f":[
      {"d":"Joan",
       "f":[
        "Joan.babylon",
        "Joan.jpg",
        "Joan2.babylon",
        "Joan_texture_image.jpg"
      ]},
      {"d":"skeleton",
       "f":[
        "skeleton.babylon",
        "texture.png"
      ]},
      {"d":"Vincent",
       "f":[
        "Vincent.babylon",
        "Vincent.jpg",
        "Vincent_old.babylon",
        "Vincent_texture_image.jpg"
      ]}
    ]},
    {"d":"sounds",
     "f":[
      "amb_birdtree_flyaway_01.wav",
      "birdsFlap.ogg",
      "door.mp3",
      "forest-ambient.ogg",
      "hello.mp3",
      "nature-ambiance.ogg",
      "old_door.ogg",
      "soft-forest-music.ogg",
      "tractor.wav",
      "wind.ogg"
    ]},
    {"d":"structures",
     "f":[
      {"d":"coffin",
       "f":[
        "coffin.babylon",
        "coffin.jpg",
        "diffuse.tga"
      ]},
      {"d":"farm_barn_01",
       "f":[
        "farm_barn_01.babylon",
        "farm_barn_01.jpg",
        "farm_barn_D.jpg"
      ]},
      {"d":"farm_silo_01",
       "f":[
        "farm_silo_01.babylon",
        "farm_silo_01.jpg",
        "farm_silo_D.tga"
      ]},
      {"d":"fences",
       "f":[
        "fences.babylon",
        "fences.babylon.old",
        "fences.jpg",
        "prop_fence1_col.jpg",
        "prop_fence1_nor.jpg"
      ]},
      {"d":"huts",
       "f":[
        "huts.babylon",
        "huts.jpg",
        "hut_texture.jpg"
      ]},
      {"d":"tipi",
       "f":[
        "tipi.babylon",
        "tipi.jpg",
        "tipi_texture.png"
      ]}
    ]},
    {"d":"terrains",
     "f":[
      "Heightmap.png",
      {"d":"hill1",
       "f":[
        "hill1_diffuse.jpg",
        "hill1_heightMap.png"
      ]}
    ]},
    {"d":"textures",
     "f":[
      "ground.jpg"
    ]},
    {"d":"vegetations",
     "f":[
      {"d":"farm_rocks_01",
       "f":[
        "farm_rocks_01.babylon",
        "farm_rocks_01.jpg",
        "farm_trees_rocks_flowers_D.tga"
      ]},
      {"d":"farm_stump_01",
       "f":[
        "farm_haybale_stump_shovel_wheelbarrow_rake_D.tga",
        "farm_stump_01.babylon",
        "farm_stump_01.jpg"
      ]},
      {"d":"farm_tree_01",
       "f":[
        "farm_trees_rocks_flowers_D.tga",
        "farm_tree_01.babylon",
        "farm_tree_01.jpg",
        "farm_tree_02.babylon"
      ]},
      {"d":"grass",
       "f":[
        "grass.babylon",
        "gs.tga"
      ]},
      {"d":"grass2",
       "f":[
        "g1.tga",
        "g3.tga",
        "g4.tga",
        "g5.tga",
        "g6.tga",
        "grass2.babylon"
      ]},
      {"d":"grass3",
       "f":[
        "g1.tga",
        "grass3.babylon"
      ]},
      {"d":"shrub-1",
       "f":[
        "s1.tga",
        "shrub-1.babylon"
      ]},
      {"d":"shrub-9",
       "f":[
        "s1.tga",
        "shrub-9.babylon"
      ]},
      {"d":"tree1",
       "f":[
        "tree1.babylon",
        "tree1.jpg",
        "trees_bark_002_col.jpg",
        "trees_bark_002_nor.jpg",
        "trees_leaves_003_col.png"
      ]},
      {"d":"tree2",
       "f":[
        "Tree.tga",
        "tree2.babylon",
        "tree2.jpg"
      ]}
    ]},
    {"d":"vehicles",
     "f":[
      {"d":"farm_tractor_01",
       "f":[
        "doc1.jpg",
        "farm_tractor_01.babylon",
        "farm_tractor_01.jpg",
        "farm_tractor_D.tga"
      ]}
    ]}
  ]},
  "config.js",
  {"d":"internal",
   "f":[
    {"d":"assets",
     "f":[
      {"d":"primitives",
       "f":[
        {"d":"box",
         "f":[
          "box.jpg"
        ]},
        {"d":"cone",
         "f":[
          "cone.jpg"
        ]},
        {"d":"cylinder",
         "f":[
          "cylinder.jpg"
        ]},
        {"d":"disc",
         "f":[
          "disc.jpg"
        ]},
        {"d":"plane",
         "f":[
          "plane.jpg"
        ]},
        {"d":"sphere",
         "f":[
          "sphere.jpg"
        ]},
        {"d":"torus",
         "f":[
          "torus.jpg"
        ]}
      ]},
      {"d":"skyboxes",
       "f":[
        {"d":"city",
         "f":[
          "city.jpg",
          "city_nx.jpg",
          "city_ny.jpg",
          "city_nz.jpg",
          "city_px.jpg",
          "city_py.jpg",
          "city_pz.jpg"
        ]},
        {"d":"desert",
         "f":[
          "desert.jpg",
          "desert_nx.jpg",
          "desert_ny.jpg",
          "desert_nz.jpg",
          "desert_px.jpg",
          "desert_py.jpg",
          "desert_pz.jpg"
        ]},
        {"d":"dusk",
         "f":[
          "dusk.jpg",
          "dusk_nx.jpg",
          "dusk_ny.jpg",
          "dusk_nz.jpg",
          "dusk_px.jpg",
          "dusk_py.jpg",
          "dusk_pz.jpg"
        ]},
        {"d":"hilly",
         "f":[
          "hilly.jpg",
          "hilly_nx.jpg",
          "hilly_ny.jpg",
          "hilly_nz.jpg",
          "hilly_px.jpg",
          "hilly_py.jpg",
          "hilly_pz.jpg"
        ]},
        {"d":"hot",
         "f":[
          "hot.jpg",
          "hot_nx.jpg",
          "hot_ny.jpg",
          "hot_nz.jpg",
          "hot_px.jpg",
          "hot_py.jpg",
          "hot_pz.jpg"
        ]},
        {"d":"moon",
         "f":[
          "moon.jpg",
          "moon_nx.jpg",
          "moon_ny.jpg",
          "moon_nz.jpg",
          "moon_px.jpg",
          "moon_py.jpg",
          "moon_pz.jpg"
        ]},
        {"d":"rain",
         "f":[
          "rain.jpg",
          "rain_nx.jpg",
          "rain_ny.jpg",
          "rain_nz.jpg",
          "rain_px.jpg",
          "rain_py.jpg",
          "rain_pz.jpg"
        ]},
        {"d":"snow1",
         "f":[
          "snow1.jpg",
          "snow1_nx.jpg",
          "snow1_ny.jpg",
          "snow1_nz.jpg",
          "snow1_px.jpg",
          "snow1_py.jpg",
          "snow1_pz.jpg"
        ]},
        {"d":"TropicalSunnyDay",
         "f":[
          "TropicalSunnyDay.jpg",
          "TropicalSunnyDay_nx.jpg",
          "TropicalSunnyDay_ny.jpg",
          "TropicalSunnyDay_nz.jpg",
          "TropicalSunnyDay_px.jpg",
          "TropicalSunnyDay_py.jpg",
          "TropicalSunnyDay_pz.jpg"
        ]}
      ]}
    ]},
    {"d":"avatar",
     "f":[
      "starterAvatars.babylon",
      "starterAvatars.babylon.old",
      "Vincent_texture_image.jpg"
    ]},
    {"d":"textures",
     "f":[
      "basswood.jpg",
      "Birch.jpg",
      "earth.jpg",
      "flare.png",
      "ground-1.jpg",
      "ground-normal-0.png",
      "ground-normal.jpg",
      "ground-normal.png",
      "ground.jpg",
      "ground_heightMap.png",
      "ground_heightMap1.png",
      "ground_heightMap_bkup.png",
      "no-texture.jpg",
      "raindrop-1.png",
      "raindrop-2.png",
      {"d":"skybox-default",
       "f":[
        "default.jpg",
        "default_nx.jpg",
        "default_ny.jpg",
        "default_nz.jpg",
        "default_px.jpg",
        "default_py.jpg",
        "default_pz.jpg"
      ]},
      "tga-image.jpg",
      "water.jpg",
      "wood.jpg",
      "worldHeightMap.jpg"
    ]}
  ]},
  "u.bat",
  "updateAssets.js",
  "vishvaFiles.js",
  {"d":"worlds",
   "f":[
    "babylon.d.ts",
    "demo-terrain-fixed.js",
    "demo.js",
    "demo1.js",
    "demo_backup.js",
    "greenery.js",
    "groundSPS.js",
    "junk.js",
    "myworld4.js",
    "myworld5.js",
    "spsDemo.js",
    "test-ava.js"
  ]}
]