vishvaFiles=[
  {"d":"assets",
   "f":[
    {"d":"characters",
     "f":[
      {"d":"deer",
       "f":[
        "deer.glb"
      ]},
      {"d":"insect",
       "f":[
        "insect.glb"
      ]},
      {"d":"Jamik",
       "f":[
        "GD_Jamik.png",
        "Jamik.babylon",
        "Jamik.babylon.manifest",
        "Jamik2.babylon"
      ]},
      {"d":"Joan",
       "f":[
        "Joan.babylon",
        "Joan.jpg",
        "Joan2.babylon",
        "Joan_texture_image.jpg"
      ]},
      {"d":"minotour001",
       "f":[
        "mino01.jpg",
        "minotour001.bakup.glb",
        "minotour001.glb",
        "minotour001.mtl",
        "minotour001.obj"
      ]},
      "newalex.bin",
      "newalex.gltf",
      {"d":"NPC",
       "f":[
        "NPC.babylon",
        {"d":"NPC.fbm",
         "f":[
          "169aba19.jpg",
          "3b6c645d.jpg",
          "575d1bef.png",
          "8c6f6e56.jpg",
          "91bb8e40.jpg",
          "c4e48af6.jpg"
        ]}
      ]},
      {"d":"skeleton",
       "f":[
        "skeleton.babylon",
        "skeleton.babylon.old",
        "skeleton.blend",
        "skeleton.log",
        "texture.png"
      ]},
      {"d":"test3",
       "f":[
        "test3.babylon",
        "young_lightskinned_female_diffuse.png"
      ]},
      {"d":"test5",
       "f":[
        "brown_eye.png",
        "male_casualsuit06_diffuse.png",
        "old_lightskinned_male_diffuse.png",
        "shoes02_diffuse.png",
        "test5.babylon"
      ]},
      {"d":"Vincent",
       "f":[
        "Vincent.babylon",
        "Vincent.jpg",
        "Vincent_texture_image.jpg"
      ]},
      {"d":"vincent2",
       "f":[
        "vincent2.glb"
      ]}
    ]},
    {"d":"misc",
     "f":[
      {"d":"DeadProject Goal2",
       "f":[
        {"d":"DeadProject Goal1",
         "f":[
          {"d":"audio",
           "f":[
            {"d":"sounds",
             "f":[
              "door_steam.wav",
              "door_steam_close.wav",
              "enem_crooked_att1.wav",
              "enem_crooked_att2.wav",
              "enem_crooked_dead1.wav",
              "enem_crooked_dead2.wav",
              "enem_crooked_hit1.wav",
              "enem_crooked_hit2.wav",
              "foot_steps_att_1.wav",
              "sfx_chainsaw_active_1.wav",
              "sfx_chainsaw_active_2.wav",
              "sfx_chainsaw_end.wav",
              "sfx_chainsaw_idle_1.wav",
              "sfx_chainsaw_idle_2.wav",
              "sfx_chainsaw_idle_3.wav",
              "sfx_computer_bleep_1.wav",
              "sfx_explosion_1_temporary.wav",
              "sfx_fire_burning.wav",
              "sfx_freezegun_fire_1.wav",
              "sfx_freeze_gun_WIP.wav",
              "sfx_gunshot5.wav",
              "sfx_gunshot6.wav",
              "sfx_large_cell_blown.wav",
              "sfx_ricochet1.wav",
              "sfx_ricochet2.wav",
              "sfx_ricochet3.wav",
              "sfx_ricochet4.wav",
              "sfx_rocket_launch_1.wav",
              "sfx_rocket_launch_2.wav",
              "sfx_shotgun_fire_1.wav",
              "sfx_shotgun_fire_2.wav",
              "sfx_shotgun_reload_2.wav",
              "sfx_tcell_blown.wav",
              "sfx_window_break_1.wav",
              "sfx_window_break_big_1.wav",
              "sfx_window_break_big_2.wav",
              "sfx_window_break_big_3.wav"
            ]}
          ]},
          {"d":"Chars",
           "f":[
            "player.blend"
          ]},
          {"d":"Documentation",
           "f":[
            "doc_1.png",
            "doc_2.png",
            "light_doc1.png",
            "light_doc2.png"
          ]},
          {"d":"enemies",
           "f":[
            "CH1.blend",
            "ch2.blend"
          ]},
          "enemies_playground.blend",
          {"d":"levels",
           "f":[
            "enviro_super_test.blend",
            "level.blend",
            {"d":"Props",
             "f":[
              "Props_packed.blend"
            ]}
          ]},
          {"d":"optilighting",
           "f":[
            "lighting optimized.blend",
            "read the docs.txt"
          ]},
          {"d":"player",
           "f":[
            "player.blend",
            "player.blend1",
            "player.blend2"
          ]},
          {"d":"textures",
           "f":[
            "ammo_box_col.dds",
            "ammo_box_nrm2.dds",
            "dec_explosion_hole.png",
            "dec_glow_random.png",
            "dec_liquid_pool.png",
            "dec_liquid_pool_NRM.dds",
            "dec_liquid_pool_NRM.tga",
            "dec_paper_warning.png",
            "dec_part_points.png",
            "dec_scratches_alpha.png",
            "dec_shattering_glass.png",
            "dec_splatters_mask_cpoy.png",
            "dec_weapon_fx.png",
            "dec_wind_mask.png",
            "disort_noise.png",
            "enem2_col.png",
            "enem_1_col.png",
            "enem_1_nrm.png",
            "enem_1_spc.png",
            "enem_2_nrm.png",
            "enem_2_spec.png",
            "grill_floors.png",
            "large_generator_1_col.dds",
            "large_generator_1_nrm.dds",
            "large_generator_1_nrm.tga",
            "metal_metal_burned.dds",
            "metal_metal_burned_NRM.dds",
            "modular_texture.dds",
            "modular_texture_2_COL.dds",
            "modular_texture_2_NRM.dds",
            "modular_texture_NRM.dds",
            "part_fire_steam_electricity.png",
            "point_spot.png",
            "ref_map_cubic.dds",
            "text_various.png",
            "text_various_2.dds",
            "trashes.png",
            "trashes_nrm.png",
            "trash_cont_col.dds",
            "trash_cont_nrm.dds",
            {"d":"weapons",
             "f":[
              "chain_saw_col.dds",
              "chain_saw_nrm.tga",
              "DBar_Shotgun_col.dds",
              "DBar_Shotgun_NRM.tga",
              "freeze_fun_nrm.tga",
              "freeze_gun_col.dds",
              "rocket_launcher_col.dds",
              "rocket_launcher_nrm.tga"
            ]}
          ]},
          "update..read.txt",
          {"d":"weapons",
           "f":[
            "high_poly_wp.blend",
            "weapons_pack.blend"
          ]},
          "weapon_fx.blend"
        ]}
      ]}
    ]},
    {"d":"sounds",
     "f":[
      "amb_birdtree_flyaway_01.wav",
      "birdsFlap.ogg",
      "door.mp3",
      "forest-ambient.ogg",
      "hello.mp3",
      "nature-ambiance.ogg",
      "old_door.ogg",
      "soft-forest-music.ogg",
      "tractor.wav",
      "wind.ogg"
    ]},
    {"d":"structures",
     "f":[
      {"d":"coffin",
       "f":[
        "coffin.babylon",
        "coffin.jpg",
        "diffuse.tga"
      ]},
      {"d":"farm_barn_01",
       "f":[
        "farm_barn_01.babylon",
        "farm_barn_01.jpg",
        "farm_barn_D.jpg"
      ]},
      {"d":"farm_silo_01",
       "f":[
        "farm_silo_01.babylon",
        "farm_silo_01.jpg",
        "farm_silo_D.tga"
      ]},
      {"d":"fences",
       "f":[
        "fences.babylon",
        "fences.babylon.old",
        "fences.jpg",
        "prop_fence1_col.jpg",
        "prop_fence1_nor.jpg"
      ]},
      {"d":"gate",
       "f":[
        "gate.babylon"
      ]},
      {"d":"huts",
       "f":[
        "huts.babylon",
        "huts.jpg",
        "hut_texture.jpg"
      ]},
      {"d":"medieval",
       "f":[
        {"d":"75519_House1Upload_blend",
         "f":[
          "75519 - Medieval houses - License.html",
          "DoorType1_1.jpg",
          "DoorType1_2.jpg",
          "GreyBricks2.jpg",
          "GreyStone2.jpg",
          "House1Upload.babylon",
          "House1Upload.blend",
          "House1Upload.log",
          "PlasterLarge.jpg",
          "preview_75519.jpg",
          "RoofTiles.jpg",
          "Rusted Metal.jpg",
          "Stone.jpg",
          "TreeLogEdgeWeathered.jpg",
          "WindowBlue1.jpg",
          "WindowsBlue2.jpg",
          "Wood.jpg"
        ]},
        "75519_House1Upload_blend.zip",
        {"d":"75861_House2_1Upload_blend",
         "f":[
          "75861 - Medieval House - License.html",
          "House2_1Upload.blend",
          "preview_75861.jpg"
        ]},
        "75861_House2_1Upload_blend.zip",
        {"d":"75862_House3Upload_blend",
         "f":[
          "75862 - Medieval house - License.html",
          "House3Upload.blend",
          "preview_75862.jpg"
        ]},
        "75862_House3Upload_blend.zip",
        {"d":"75864_House4Upload_blend",
         "f":[
          "75864 - Medieval House - License.html",
          "House4Upload.blend",
          "preview_75864.jpg"
        ]},
        "75864_House4Upload_blend.zip",
        "Medieval Props textured - OpenGameArt.org.url",
        "rts_props.blend"
      ]},
      {"d":"scene",
       "f":[
        "AUTHOR",
        "LICENSE",
        "scene.bin",
        "scene.gltf",
        {"d":"textures",
         "f":[
          "Bordo_Zolla_01_Mat_baseColor.jpg",
          "Bordo_Zolla_02_Mat_baseColor.jpg",
          "Erba_01_TileMat_baseColor.jpg",
          "Mura_01_TileMat_baseColor.jpg",
          "Mura_03_TileMat_baseColor.jpg",
          "Passerella_Legno_TopMura_02_Mat_baseColor.jpg",
          "Passerella_Legno_TopMura_TileMura_baseColor.jpg",
          "Terreno_TileMat_1_baseColor.jpg",
          "Terreno_TileMat_2_baseColor.jpg",
          "Terreno_TileMat_3_baseColor.jpg",
          "Terreno_TileMat_4_baseColor.jpg",
          "Terreno_TileMat_7_baseColor.jpg",
          "Terreno_TileMat_8_baseColor.jpg",
          "Terreno_TileMat_9_baseColor.jpg"
        ]}
      ]},
      {"d":"tipi",
       "f":[
        "tipi.babylon",
        "tipi.jpg",
        "tipi_texture.png"
      ]},
      {"d":"tower_lowpoly",
       "f":[
        "tower_lowpoly.jpg",
        "tower_lowpoly.obj",
        "tower_lowpoly_normals.jpg"
      ]}
    ]},
    {"d":"terrains",
     "f":[
      "Heightmap.png",
      {"d":"hill1",
       "f":[
        "hill1_diffuse.jpg",
        "hill1_heightMap.png"
      ]}
    ]},
    {"d":"textures",
     "f":[
      "ground.jpg"
    ]},
    {"d":"vegetations",
     "f":[
      {"d":"farm_rocks_01",
       "f":[
        "farm_rocks_01.babylon",
        "farm_rocks_01.jpg",
        "farm_trees_rocks_flowers_D.tga"
      ]},
      {"d":"farm_stump_01",
       "f":[
        "farm_haybale_stump_shovel_wheelbarrow_rake_D.tga",
        "farm_stump_01.babylon",
        "farm_stump_01.jpg"
      ]},
      {"d":"farm_tree_01",
       "f":[
        "farm_trees_rocks_flowers_D.tga",
        "farm_tree_01.babylon",
        "farm_tree_01.jpg",
        "farm_tree_02.babylon"
      ]},
      {"d":"grass",
       "f":[
        "grass.babylon",
        "gs.tga"
      ]},
      {"d":"grass2",
       "f":[
        "g1.tga",
        "g3.tga",
        "g4.tga",
        "g5.tga",
        "g6.tga",
        "grass2.babylon"
      ]},
      {"d":"grass3",
       "f":[
        "g1.tga",
        "grass3.babylon"
      ]},
      {"d":"shrub-1",
       "f":[
        "s1.tga",
        "shrub-1.babylon"
      ]},
      {"d":"shrub-9",
       "f":[
        "s1.tga",
        "shrub-9.babylon"
      ]},
      {"d":"tree1",
       "f":[
        "tree1.babylon",
        "tree1.jpg",
        "trees_bark_002_col.jpg",
        "trees_bark_002_nor.jpg",
        "trees_leaves_003_col.png"
      ]},
      {"d":"tree2",
       "f":[
        "Tree.tga",
        "tree2.babylon",
        "tree2.jpg"
      ]}
    ]},
    {"d":"vehicles",
     "f":[
      {"d":"farm_tractor_01",
       "f":[
        "doc1.jpg",
        "farm_tractor_01.babylon",
        "farm_tractor_01.jpg",
        "farm_tractor_D.tga"
      ]}
    ]}
  ]},
  "config.js",
  {"d":"internal",
   "f":[
    {"d":"assets",
     "f":[
      {"d":"primitives",
       "f":[
        {"d":"box",
         "f":[
          "box.jpg"
        ]},
        {"d":"cone",
         "f":[
          "cone.jpg"
        ]},
        {"d":"cylinder",
         "f":[
          "cylinder.jpg"
        ]},
        {"d":"disc",
         "f":[
          "disc.jpg"
        ]},
        {"d":"plane",
         "f":[
          "plane.jpg"
        ]},
        {"d":"sphere",
         "f":[
          "sphere.jpg"
        ]},
        {"d":"torus",
         "f":[
          "torus.jpg"
        ]}
      ]},
      {"d":"skyboxes",
       "f":[
        {"d":"city",
         "f":[
          "city.jpg",
          "city_nx.jpg",
          "city_ny.jpg",
          "city_nz.jpg",
          "city_px.jpg",
          "city_py.jpg",
          "city_pz.jpg"
        ]},
        {"d":"desert",
         "f":[
          "desert.jpg",
          "desert_nx.jpg",
          "desert_ny.jpg",
          "desert_nz.jpg",
          "desert_px.jpg",
          "desert_py.jpg",
          "desert_pz.jpg"
        ]},
        {"d":"dusk",
         "f":[
          "dusk.jpg",
          "dusk_nx.jpg",
          "dusk_ny.jpg",
          "dusk_nz.jpg",
          "dusk_px.jpg",
          "dusk_py.jpg",
          "dusk_pz.jpg"
        ]},
        {"d":"hilly",
         "f":[
          "hilly.jpg",
          "hilly_nx.jpg",
          "hilly_ny.jpg",
          "hilly_nz.jpg",
          "hilly_px.jpg",
          "hilly_py.jpg",
          "hilly_pz.jpg"
        ]},
        {"d":"hot",
         "f":[
          "hot.jpg",
          "hot_nx.jpg",
          "hot_ny.jpg",
          "hot_nz.jpg",
          "hot_px.jpg",
          "hot_py.jpg",
          "hot_pz.jpg"
        ]},
        {"d":"moon",
         "f":[
          "moon.jpg",
          "moon_nx.jpg",
          "moon_ny.jpg",
          "moon_nz.jpg",
          "moon_px.jpg",
          "moon_py.jpg",
          "moon_pz.jpg"
        ]},
        {"d":"rain",
         "f":[
          "rain.jpg",
          "rain_nx.jpg",
          "rain_ny.jpg",
          "rain_nz.jpg",
          "rain_px.jpg",
          "rain_py.jpg",
          "rain_pz.jpg"
        ]},
        {"d":"snow1",
         "f":[
          "snow1.jpg",
          "snow1_nx.jpg",
          "snow1_ny.jpg",
          "snow1_nz.jpg",
          "snow1_px.jpg",
          "snow1_py.jpg",
          "snow1_pz.jpg"
        ]},
        {"d":"TropicalSunnyDay",
         "f":[
          "TropicalSunnyDay.jpg",
          "TropicalSunnyDay_nx.jpg",
          "TropicalSunnyDay_ny.jpg",
          "TropicalSunnyDay_nz.jpg",
          "TropicalSunnyDay_px.jpg",
          "TropicalSunnyDay_py.jpg",
          "TropicalSunnyDay_pz.jpg"
        ]}
      ]}
    ]},
    {"d":"avatar",
     "f":[
      "starterAvatars.babylon",
      "starterAvatars.babylon.old",
      "Vincent_texture_image.jpg"
    ]},
    {"d":"textures",
     "f":[
      "basswood.jpg",
      "Birch.jpg",
      "earth.jpg",
      "flare.png",
      "ground-normal-0.png",
      "ground-normal.jpg",
      "ground-normal.png",
      "ground.jpg",
      "ground_heightMap.png",
      "ground_heightMap_bkup.png",
      "no-texture.jpg",
      "raindrop-1.png",
      "raindrop-2.png",
      {"d":"skybox-default",
       "f":[
        "default_nx.jpg",
        "default_ny.jpg",
        "default_nz.jpg",
        "default_px.jpg",
        "default_py.jpg",
        "default_pz.jpg"
      ]},
      "tga-image.jpg",
      "water.jpg",
      "wood.jpg",
      "worldHeightMap.jpg"
    ]}
  ]},
  "u.bat",
  "updateAssets.js",
  "vishvaFiles.js",
  {"d":"worlds",
   "f":[
    "babylon.d.ts",
    "demo.js",
    "demo1.js",
    "demo2.js",
    "demo_backup.js",
    "dr.js",
    "greenery.js",
    "groundSPS.js",
    "groundSPS2.js",
    "junk.js",
    "junkasset.js",
    "myworld4.js",
    "myworld5.js"
  ]}
]