vishvaFiles=[
  {"d":"assets",
   "f":[
    {"d":"characters",
     "f":[
      {"d":"deer",
       "f":[
        "deer.glb"
      ]},
      {"d":"insect",
       "f":[
        "insect.glb"
      ]},
      {"d":"Joan",
       "f":[
        "Joan.babylon",
        "Joan.jpg",
        "Joan_texture_image.jpg"
      ]},
      {"d":"minotour001",
       "f":[
        "mino01.jpg",
        "minotour001.bakup.glb",
        "minotour001.glb",
        "minotour001.mtl",
        "minotour001.obj"
      ]},
      {"d":"NPC",
       "f":[
        "NPC.babylon",
        "npc.blend",
        "npc.blend1",
        "NPC.log"
      ]},
      {"d":"skeleton",
       "f":[
        "skeleton.babylon",
        "skeleton.babylon.old",
        "skeleton.blend",
        "skeleton.log",
        "texture.png"
      ]},
      {"d":"test3",
       "f":[
        "test3.babylon",
        "young_lightskinned_female_diffuse.png"
      ]},
      {"d":"test5",
       "f":[
        "brown_eye.png",
        "male_casualsuit06_diffuse.png",
        "old_lightskinned_male_diffuse.png",
        "shoes02_diffuse.png",
        "test5.babylon"
      ]},
      {"d":"Vincent",
       "f":[
        "Vincent.babylon",
        "Vincent.jpg",
        "Vincent_texture_image.jpg"
      ]},
      {"d":"vincent2",
       "f":[
        "vincent2.glb"
      ]}
    ]},
    {"d":"primitives",
     "f":[
      {"d":"box",
       "f":[
        "box.jpg"
      ]},
      {"d":"cone",
       "f":[
        "cone.jpg"
      ]},
      {"d":"cylinder",
       "f":[
        "cylinder.jpg"
      ]},
      {"d":"disc",
       "f":[
        "disc.jpg"
      ]},
      {"d":"plane",
       "f":[
        "plane.jpg"
      ]},
      {"d":"sphere",
       "f":[
        "sphere.jpg"
      ]},
      {"d":"torus",
       "f":[
        "torus.jpg"
      ]}
    ]},
    {"d":"skyboxes",
     "f":[
      {"d":"city",
       "f":[
        "city.jpg",
        "city_nx.jpg",
        "city_ny.jpg",
        "city_nz.jpg",
        "city_px.jpg",
        "city_py.jpg",
        "city_pz.jpg"
      ]},
      {"d":"desert",
       "f":[
        "desert.jpg",
        "desert_nx.jpg",
        "desert_ny.jpg",
        "desert_nz.jpg",
        "desert_px.jpg",
        "desert_py.jpg",
        "desert_pz.jpg"
      ]},
      {"d":"dusk",
       "f":[
        "dusk.jpg",
        "dusk_nx.jpg",
        "dusk_ny.jpg",
        "dusk_nz.jpg",
        "dusk_px.jpg",
        "dusk_py.jpg",
        "dusk_pz.jpg"
      ]},
      {"d":"hilly",
       "f":[
        "hilly.jpg",
        "hilly_nx.jpg",
        "hilly_ny.jpg",
        "hilly_nz.jpg",
        "hilly_px.jpg",
        "hilly_py.jpg",
        "hilly_pz.jpg"
      ]},
      {"d":"hot",
       "f":[
        "hot.jpg",
        "hot_nx.jpg",
        "hot_ny.jpg",
        "hot_nz.jpg",
        "hot_px.jpg",
        "hot_py.jpg",
        "hot_pz.jpg"
      ]},
      {"d":"moon",
       "f":[
        "moon.jpg",
        "moon_nx.jpg",
        "moon_ny.jpg",
        "moon_nz.jpg",
        "moon_px.jpg",
        "moon_py.jpg",
        "moon_pz.jpg"
      ]},
      {"d":"rain",
       "f":[
        "rain.jpg",
        "rain_nx.jpg",
        "rain_ny.jpg",
        "rain_nz.jpg",
        "rain_px.jpg",
        "rain_py.jpg",
        "rain_pz.jpg"
      ]},
      {"d":"snow1",
       "f":[
        "snow1.jpg",
        "snow1_nx.jpg",
        "snow1_ny.jpg",
        "snow1_nz.jpg",
        "snow1_px.jpg",
        "snow1_py.jpg",
        "snow1_pz.jpg"
      ]},
      {"d":"TropicalSunnyDay",
       "f":[
        "TropicalSunnyDay.jpg",
        "TropicalSunnyDay_nx.jpg",
        "TropicalSunnyDay_ny.jpg",
        "TropicalSunnyDay_nz.jpg",
        "TropicalSunnyDay_px.jpg",
        "TropicalSunnyDay_py.jpg",
        "TropicalSunnyDay_pz.jpg"
      ]}
    ]},
    {"d":"sounds",
     "f":[
      "amb_birdtree_flyaway_01.wav",
      "birdsFlap.ogg",
      "door.mp3",
      "forest-ambient.ogg",
      "hello.mp3",
      "nature-ambiance.ogg",
      "old_door.ogg",
      "soft-forest-music.ogg",
      "tractor.wav",
      "wind.ogg"
    ]},
    {"d":"structures",
     "f":[
      {"d":"coffin",
       "f":[
        "coffin.babylon",
        "coffin.jpg",
        "diffuse.tga"
      ]},
      {"d":"farm_barn_01",
       "f":[
        "farm_barn_01.babylon",
        "farm_barn_01.jpg",
        "farm_barn_D.jpg"
      ]},
      {"d":"farm_silo_01",
       "f":[
        "farm_silo_01.babylon",
        "farm_silo_01.jpg",
        "farm_silo_D.tga"
      ]},
      {"d":"fences",
       "f":[
        "fences.babylon",
        "fences.babylon.old",
        "fences.jpg",
        "prop_fence1_col.jpg",
        "prop_fence1_nor.jpg"
      ]},
      {"d":"gate",
       "f":[
        "gate.babylon"
      ]},
      {"d":"huts",
       "f":[
        "huts.babylon",
        "huts.jpg",
        "hut_texture.jpg"
      ]},
      {"d":"scene",
       "f":[
        "AUTHOR",
        "LICENSE",
        "scene.bin",
        "scene.gltf",
        {"d":"textures",
         "f":[
          "Bordo_Zolla_01_Mat_baseColor.jpg",
          "Bordo_Zolla_02_Mat_baseColor.jpg",
          "Erba_01_TileMat_baseColor.jpg",
          "Mura_01_TileMat_baseColor.jpg",
          "Mura_03_TileMat_baseColor.jpg",
          "Passerella_Legno_TopMura_02_Mat_baseColor.jpg",
          "Passerella_Legno_TopMura_TileMura_baseColor.jpg",
          "Terreno_TileMat_1_baseColor.jpg",
          "Terreno_TileMat_2_baseColor.jpg",
          "Terreno_TileMat_3_baseColor.jpg",
          "Terreno_TileMat_4_baseColor.jpg",
          "Terreno_TileMat_7_baseColor.jpg",
          "Terreno_TileMat_8_baseColor.jpg",
          "Terreno_TileMat_9_baseColor.jpg"
        ]}
      ]},
      {"d":"tipi",
       "f":[
        "tipi.babylon",
        "tipi.jpg",
        "tipi_texture.png"
      ]},
      {"d":"tower_lowpoly",
       "f":[
        "tower_lowpoly.jpg",
        "tower_lowpoly.obj",
        "tower_lowpoly_normals.jpg"
      ]}
    ]},
    {"d":"terrains",
     "f":[
      "Heightmap.png",
      {"d":"hill1",
       "f":[
        "hill1_diffuse.jpg",
        "hill1_heightMap.png"
      ]}
    ]},
    {"d":"textures",
     "f":[
      "ground.jpg"
    ]},
    {"d":"vegetations",
     "f":[
      {"d":"farm_rocks_01",
       "f":[
        "farm_rocks_01.babylon",
        "farm_rocks_01.jpg",
        "farm_trees_rocks_flowers_D.tga"
      ]},
      {"d":"farm_stump_01",
       "f":[
        "farm_haybale_stump_shovel_wheelbarrow_rake_D.tga",
        "farm_stump_01.babylon",
        "farm_stump_01.jpg"
      ]},
      {"d":"farm_tree_01",
       "f":[
        "farm_trees_rocks_flowers_D.tga",
        "farm_tree_01.babylon",
        "farm_tree_01.jpg"
      ]},
      {"d":"grass",
       "f":[
        "grass.babylon",
        "gs.tga"
      ]},
      {"d":"grass2",
       "f":[
        "g1.tga",
        "g3.tga",
        "g4.tga",
        "g5.tga",
        "g6.tga",
        "grass2.babylon"
      ]},
      {"d":"grass3",
       "f":[
        "g1.tga",
        "grass3.babylon"
      ]},
      {"d":"shrub-1",
       "f":[
        "s1.tga",
        "shrub-1.babylon"
      ]},
      {"d":"shrub-9",
       "f":[
        "s1.tga",
        "shrub-9.babylon"
      ]},
      {"d":"tree1",
       "f":[
        "tree1.babylon",
        "tree1.jpg",
        "trees_bark_002_col.jpg",
        "trees_bark_002_nor.jpg",
        "trees_leaves_003_col.png"
      ]},
      {"d":"tree2",
       "f":[
        "Tree.tga",
        "tree2.babylon",
        "tree2.jpg"
      ]}
    ]},
    {"d":"vehicles",
     "f":[
      {"d":"farm_tractor_01",
       "f":[
        "doc1.jpg",
        "farm_tractor_01.babylon",
        "farm_tractor_01.jpg",
        "farm_tractor_D.tga"
      ]}
    ]}
  ]},
  "assets.js",
  "config.js",
  {"d":"internal",
   "f":[
    {"d":"avatar",
     "f":[
      "starterAvatars.babylon",
      "starterAvatars.babylon.old",
      "Vincent_texture_image.jpg"
    ]},
    {"d":"textures",
     "f":[
      "basswood.jpg",
      "Birch.jpg",
      "earth.jpg",
      "flare.png",
      "ground-normal-0.png",
      "ground-normal.jpg",
      "ground-normal.png",
      "ground.jpg",
      "ground_heightMap.png",
      "no-texture.jpg",
      "raindrop-1.png",
      "raindrop-2.png",
      {"d":"skybox-default",
       "f":[
        "default_nx.jpg",
        "default_ny.jpg",
        "default_nz.jpg",
        "default_px.jpg",
        "default_py.jpg",
        "default_pz.jpg"
      ]},
      "tga-image.jpg",
      "wood.jpg",
      "worldHeightMap.jpg"
    ]}
  ]},
  "updateAssets.js",
  "vishvaFiles.js",
  {"d":"worlds",
   "f":[
    "demo.js",
    "demo1.js",
    "demo2.js",
    "demo_backup.js",
    "dr.js",
    "greenery.js",
    "junk.js",
    "junkasset.js",
    "myworld4.js",
    "myworld5.js"
  ]}
];