userAssets=[
  {"d":"curated",
   "f":[
    {"d":"skyboxes",
     "f":[
      {"d":"desert",
       "f":[
        "desert_nx.jpg",
        "desert_ny.jpg",
        "desert_nz.jpg",
        "desert_px.jpg",
        "desert_py.jpg",
        "desert_pz.jpg",
        "thumbnail.png"
      ]}
    ]}
  ]}
]