vishvaFiles=[
  {"d":"assets",
   "f":[
    {"d":"characters",
     "f":[
      "fish.glb",
      "insect.glb",
      "Male_Casual.babylon",
      "Male_Casual2.babylon",
      "Tie.png"
    ]},
    {"d":"sounds",
     "f":[
      "amb_birdtree_flyaway_01.wav",
      "birdsFlap.ogg",
      "door.mp3",
      "forest-ambient.ogg",
      "Forest_Ambience.ogg",
      "Forest_Ambience2.ogg",
      "hello.mp3",
      "nature-ambiance.ogg",
      "npc_skeleton_conscious_01_lp.wav",
      "old_door-2.ogg",
      "old_door.ogg",
      "soft-forest-music.ogg",
      "tractor.wav",
      "wind.ogg"
    ]},
    {"d":"structures",
     "f":[
      "Box.gltf",
      "Box0.bin",
      "TallWall.mtl",
      "TallWall.obj"
    ]},
    {"d":"terrains",
     "f":[
      "Heightmap.png",
      {"d":"hill1",
       "f":[
        "hill1_diffuse.jpg",
        "hill1_heightMap.png"
      ]}
    ]},
    {"d":"textures",
     "f":[
      "ground.jpg"
    ]},
    {"d":"vegetations",
     "f":[
      {"d":"grass",
       "f":[
        "grass.babylon",
        "gs.tga"
      ]},
      {"d":"grass2",
       "f":[
        "g1.tga",
        "g3.tga",
        "g4.tga",
        "g5.tga",
        "g6.tga",
        "grass2.babylon"
      ]},
      {"d":"grass3",
       "f":[
        "g1.tga",
        "grass3.babylon"
      ]},
      {"d":"shrub-1",
       "f":[
        "s1.tga",
        "shrub-1.babylon"
      ]},
      {"d":"shrub-9",
       "f":[
        "s1.tga",
        "shrub-9.babylon"
      ]},
      {"d":"trees3",
       "f":[
        "trees-2.babylon",
        "trees_bark_001_col.jpg",
        "trees_bark_001_nor.jpg",
        "trees_bark_002_col.jpg",
        "trees_bark_002_nor.jpg",
        "trees_leaves_003_col.png",
        "trees_leaves_004_col.png",
        "trees_log_001_col.png",
        "trees_log_001_nor.jpg",
        "trees_vines_001_col.png",
        "tree_stumps_col.jpg",
        "tree_stumps_nor.jpg"
      ]}
    ]}
  ]},
  "config.js",
  {"d":"curated",
   "f":[
    {"d":"assets",
     "f":[
      {"d":"characters",
       "f":[
        {"d":"Joan",
         "f":[
          "Joan.babylon",
          "Joan.blend",
          "Joan.log",
          "Joan_texture_image.jpg",
          "thumbnail.png"
        ]},
        {"d":"skeleton",
         "f":[
          "skeleton.babylon",
          "texture.png"
        ]},
        {"d":"Vincent",
         "f":[
          "Vincent.babylon",
          "Vincent.blend",
          "Vincent.log",
          "Vincent_texture_image.jpg"
        ]}
      ]},
      {"d":"structures",
       "f":[
        "Box.gltf",
        "Box0.bin",
        {"d":"coffin",
         "f":[
          "coffin.babylon",
          "diffuse.tga",
          "thumbnail.png"
        ]},
        {"d":"factory",
         "f":[
          "factory.babylon",
          "factory_tex.bmp",
          "factory_tex.jpg"
        ]},
        {"d":"farm_barn_01",
         "f":[
          "farm_barn_01.babylon",
          "farm_barn_D.jpg",
          "thumbnail.png"
        ]},
        {"d":"farm_silo_01",
         "f":[
          "farm_silo_01.babylon",
          "farm_silo_D.tga",
          "thumbnail.png"
        ]},
        {"d":"fences",
         "f":[
          "fences.babylon",
          "fences.babylon.old",
          "prop_fence1_col.jpg",
          "prop_fence1_nor.jpg",
          "thumbnail.png"
        ]},
        {"d":"huts",
         "f":[
          "huts.babylon",
          "hut_texture.jpg",
          "thumbnail.png"
        ]},
        "TallWall.mtl",
        "TallWall.obj",
        {"d":"tipi",
         "f":[
          "thumbnail.png",
          "tipi.babylon",
          "tipi_texture.png"
        ]}
      ]},
      {"d":"vegetations",
       "f":[
        {"d":"farm_rocks_01",
         "f":[
          "farm_rocks_01.babylon",
          "farm_trees_rocks_flowers_D.tga",
          "thumbnail.png"
        ]},
        {"d":"farm_stump_01",
         "f":[
          "farm_haybale_stump_shovel_wheelbarrow_rake_D.tga",
          "farm_stump_01.babylon",
          "thumbnail.png"
        ]},
        {"d":"farm_tree_01",
         "f":[
          "farm_trees_rocks_flowers_D.tga",
          "farm_tree_01.babylon",
          "farm_tree_02.babylon",
          "thumbnail.png"
        ]},
        {"d":"tree1",
         "f":[
          "thumbnail.png",
          "tree1.babylon",
          "trees_bark_002_col.jpg",
          "trees_bark_002_nor.jpg",
          "trees_leaves_003_col.png"
        ]},
        {"d":"tree2",
         "f":[
          "thumbnail.png",
          "Tree.tga",
          "tree2.babylon"
        ]}
      ]},
      {"d":"vehicles",
       "f":[
        {"d":"farm_tractor_01",
         "f":[
          "doc1.jpg",
          "farm_tractor_01.babylon",
          "farm_tractor_D.tga",
          "thumbnail.png"
        ]}
      ]}
    ]}
  ]},
  {"d":"internal",
   "f":[
    {"d":"assets",
     "f":[
      {"d":"particles",
       "f":[
        {"d":"fire",
         "f":[
          "flare.png",
          "thumnail.png"
        ]},
        {"d":"smoke",
         "f":[
          "flare.png",
          "thumnail.png"
        ]}
      ]},
      {"d":"primitives",
       "f":[
        {"d":"box",
         "f":[
          "AAthumbnail.png",
          "box.jpg",
          "thumbnail.png"
        ]},
        {"d":"cone",
         "f":[
          "cone.jpg",
          "thumbnail.png"
        ]},
        {"d":"cylinder",
         "f":[
          "cylinder.jpg",
          "thumbnail.png"
        ]},
        {"d":"disc",
         "f":[
          "disc.jpg",
          "thumbnail.png"
        ]},
        {"d":"plane",
         "f":[
          "plane.jpg",
          "thumbnail.png"
        ]},
        {"d":"sphere",
         "f":[
          "sphere.jpg",
          "thumbnail.png"
        ]},
        {"d":"torus",
         "f":[
          "thumbnail.png",
          "torus.jpg"
        ]}
      ]},
      {"d":"skyboxes",
       "f":[
        {"d":"city",
         "f":[
          "city_nx.jpg",
          "city_ny.jpg",
          "city_nz.jpg",
          "city_px.jpg",
          "city_py.jpg",
          "city_pz.jpg",
          "thumbnail.png"
        ]},
        {"d":"desert",
         "f":[
          "desert_nx.jpg",
          "desert_ny.jpg",
          "desert_nz.jpg",
          "desert_px.jpg",
          "desert_py.jpg",
          "desert_pz.jpg",
          "thumbnail.png"
        ]},
        {"d":"dusk",
         "f":[
          "dusk_nx.jpg",
          "dusk_ny.jpg",
          "dusk_nz.jpg",
          "dusk_px.jpg",
          "dusk_py.jpg",
          "dusk_pz.jpg",
          "thumbnail.png"
        ]},
        {"d":"hilly",
         "f":[
          "hilly_nx.jpg",
          "hilly_ny.jpg",
          "hilly_nz.jpg",
          "hilly_px.jpg",
          "hilly_py.jpg",
          "hilly_pz.jpg",
          "thumbnail.png"
        ]},
        {"d":"hot",
         "f":[
          "hot_nx.jpg",
          "hot_ny.jpg",
          "hot_nz.jpg",
          "hot_px.jpg",
          "hot_py.jpg",
          "hot_pz.jpg",
          "thumbnail.png"
        ]},
        {"d":"moon",
         "f":[
          "moon_nx.jpg",
          "moon_ny.jpg",
          "moon_nz.jpg",
          "moon_px.jpg",
          "moon_py.jpg",
          "moon_pz.jpg",
          "thumbnail.png"
        ]},
        {"d":"rain",
         "f":[
          "rain_nx.jpg",
          "rain_ny.jpg",
          "rain_nz.jpg",
          "rain_px.jpg",
          "rain_py.jpg",
          "rain_pz.jpg",
          "thumbnail.png"
        ]},
        {"d":"snow1",
         "f":[
          "snow1_nx.jpg",
          "snow1_ny.jpg",
          "snow1_nz.jpg",
          "snow1_px.jpg",
          "snow1_py.jpg",
          "snow1_pz.jpg",
          "thumbnail.png"
        ]},
        {"d":"TropicalSunnyDay",
         "f":[
          "thumbnail.png",
          "TropicalSunnyDay_nx.jpg",
          "TropicalSunnyDay_ny.jpg",
          "TropicalSunnyDay_nz.jpg",
          "TropicalSunnyDay_px.jpg",
          "TropicalSunnyDay_py.jpg",
          "TropicalSunnyDay_pz.jpg"
        ]}
      ]}
    ]},
    {"d":"avatar",
     "f":[
      "starterAvatars.babylon",
      "Vincent.blend",
      "Vincent.jpg",
      "Vincent_texture_image.jpg"
    ]},
    {"d":"textures",
     "f":[
      "basswood.jpg",
      "Birch.jpg",
      "earth.jpg",
      "flare.png",
      "ground-1.jpg",
      "ground-normal.jpg",
      "ground-normal.png",
      "ground.jpg",
      "ground_heightMap-1.png",
      "ground_heightMap.png",
      "ground_heightMap_bkup.png",
      "no-texture.jpg",
      "raindrop-1.png",
      "raindrop-2.png",
      {"d":"skybox-default",
       "f":[
        "default.jpg",
        "default_nx.jpg",
        "default_ny.jpg",
        "default_nz.jpg",
        "default_px.jpg",
        "default_py.jpg",
        "default_pz.jpg"
      ]},
      "tga-image.jpg",
      "water.jpg",
      "waterbump.png",
      "wood.jpg",
      "worldHeightMap.jpg"
    ]}
  ]},
  "u.bat",
  "updateAssets.js",
  "vishvaFiles.js",
  {"d":"worlds",
   "f":[
    "china.js",
    "rpg.js",
    "spsDemo.js"
  ]}
]